name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 app tests

      - name: Run isort check
        run: |
          source venv/bin/activate
          isort --check-only app tests

      - name: Run black check
        run: |
          source venv/bin/activate
          black --check app tests

      - name: Run mypy
        run: |
          source venv/bin/activate
          mypy app

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
