name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort mypy pytest

      - name: Run flake8
        run: flake8 module_29_testing/hw/app module_29_testing/hw/tests

      - name: Run isort check
        run: isort --check-only module_29_testing/hw/app module_29_testing/hw/tests

      - name: Run black check
        run: black --check module_29_testing/hw/app module_29_testing/hw/tests

      - name: Run mypy
        run: mypy module_29_testing/hw/app

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q module_29_testing/hw/tests
